default_branches = ["main"]

[[repositories]]
id = "taskboard"
github = "distiya/taskboard"
clone_url = "https://github.com/distiya/taskboard.git"
local_path = "/home/disti/Documents/coding/poc/taskboard"
enabled = true
monitored_branches = []

[repositories.indexing]
languages = []
analyzers = ["tree-sitter"]
scip_enabled = true
joern_enabled = true
